# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 02:58
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BjjydyArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_and_issue', models.CharField(max_length=10, verbose_name='\u5e74\u4efd\u671f\u6570')),
                ('authors', models.CharField(max_length=20, verbose_name='\u4f5c\u8005')),
                ('title', models.CharField(max_length=50, verbose_name='\u6587\u7ae0\u540d\u79f0')),
                ('school', models.CharField(max_length=30, verbose_name='\u6240\u5728\u5b66\u6821')),
                ('section', models.CharField(max_length=10, verbose_name='\u6240\u5728\u680f\u76ee')),
                ('page_number', models.CharField(max_length=10, verbose_name='\u9875\u7801')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Kt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='\u7533\u62a5\u5e74\u4efd')),
                ('kt_type', models.CharField(choices=[(b'01', '\u6218\u7565\u8bfe\u9898'), (b'02', '\u91cd\u70b9\u8bfe\u9898'), (b'03', '\u4e00\u822c\u8bfe\u9898'), (b'04', '\u652f\u6301\u8bfe\u9898')], max_length=10, verbose_name='\u8bfe\u9898\u7c7b\u578b')),
                ('project_number', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u7f16\u53f7')),
                ('applicant', models.CharField(max_length=30, verbose_name='\u7533\u62a5\u4eba')),
                ('school', models.CharField(max_length=30, verbose_name='\u6240\u5728\u5b66\u6821')),
                ('kt_name', models.CharField(max_length=30, verbose_name='\u8bfe\u9898\u540d\u79f0')),
                ('is_completed_or_not', models.NullBooleanField(choices=[(True, '\u662f'), (False, '\u5426')], verbose_name='\u662f\u5426\u7ed3\u9879')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='\u5907\u6ce8')),
            ],
        ),
    ]
