# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bjjydyarticle',
            options={'ordering': ['-year_and_issue', '-page_number'], 'verbose_name': '\u5317\u4eac\u6559\u80b2\uff08\u5fb7\u80b2\uff09\u6587\u7ae0', 'verbose_name_plural': '\u5317\u4eac\u6559\u80b2\uff08\u5fb7\u80b2\uff09\u6587\u7ae0'},
        ),
        migrations.AlterModelOptions(
            name='kt',
            options={'ordering': ['-year', 'project_number'], 'verbose_name': '\u8bfe\u9898', 'verbose_name_plural': '\u8bfe\u9898'},
        ),
    ]
