# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomanage', '0003_auto_20181128_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kt',
            name='is_completed_or_not',
            field=models.BooleanField(choices=[(True, b'\xe6\x98\xaf'), (False, b'\xe5\x90\xa6')], default=False, verbose_name='\u662f\u5426\u7ed3\u9879'),
        ),
    ]
